site_name: String Grouper  


theme:
  name: material
  features:
    - navigation.tabs
#    - navigation.tabs.sticky

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
