name: Run tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dev-package
      run: |
        sudo apt-get install qemu tree
        python -m pip install --upgrade pip
        pip install -v -e .
        qemu-x86_64 -R 20M python time_match_strings.py
        
    
    - name: Run tests
      run: python -m unittest
